import 'package:flutter/material.dart';
import 'package:dnd_character_sheet_app/model/character_model.dart';
import 'package:dnd_character_sheet_app/model/character_option.dart';
import 'package:dnd_character_sheet_app/model/feature.dart';
import 'package:dnd_character_sheet_app/constants.dart';

class CharacterListViewModel extends ChangeNotifier {
  late List<CharacterModel> characterList;

  CharacterListViewModel() {
    // pre-generated characters
    characterList = [
      CharacterModel(
        name: "Coddrin Thunderslayer",
        charClass: barbarian,
        subclass: null,
        background: folkHero,
        race: halfOrc,
        abilityScores: [16, 14, 16, 8, 10, 8],
        spells: null,
        maxSpellSlots: null,
        currSpellSlots: null,
        maxHitPoints: 15,
        currHitPoints: 15,
        armorClass: 15,
        speed: 30,
        hitDice: 12,
      ),
      CharacterModel(
        name: "Inadi Dreithel",
        charClass: bard,
        subclass: null,
        background: entertainer,
        race: elf,
        abilityScores: [8, 16, 14, 8, 10, 16],
        spells: [viciousMockery, mageHand, dissonantWhispers, tashasHideousLaughter, healingWord, charmPerson],
        maxSpellSlots: 2,
        currSpellSlots: 2,
        maxHitPoints: 10,
        currHitPoints: 10,
        armorClass: 13,
        speed: 30,
        hitDice: 8,
      ),
      CharacterModel(
        name: "Thulmir Frozentale",
        charClass: cleric,
        subclass: lifeDomain,
        background: acolyte,
        race: dwarf,
        abilityScores: [14, 8, 16, 10, 16, 8],
        spells: [guidance, light, sacredFlame, guidingBolt, healingWord, cureWounds, bless, command, inflictWounds],
        maxSpellSlots: 2,
        currSpellSlots: 2,
        maxHitPoints: 11,
        currHitPoints: 11,
        armorClass: 9,
        speed: 30,
        hitDice: 8,
      ),
      CharacterModel(
        name: "Phibi Thunderdiggles",
        charClass: druid,
        subclass: null,
        background: hermit,
        race: gnome,
        abilityScores: [8, 14, 16, 10, 16, 8],
        spells: [druidcraft, shillelagh, entangle, goodberry, speakWithAnimals, thunderwave],
        maxSpellSlots: 2,
        currSpellSlots: 2,
        maxHitPoints: 10,
        currHitPoints: 10,
        armorClass: 12,
        speed: 30,
        hitDice: 8,
      ),
      CharacterModel(
        name: "Bellamir",
        charClass: fighter,
        subclass: null,
        background: soldier,
        race: halfElf,
        abilityScores: [16, 14, 16, 8, 10, 8],
        spells: null,
        maxSpellSlots: null,
        currSpellSlots: null,
        maxHitPoints: 12,
        currHitPoints: 12,
        armorClass: 12,
        speed: 30,
        hitDice: 10,
      ),
      CharacterModel(
        name: "Ricton Underdew",
        charClass: monk,
        subclass: null,
        background: urchin,
        race: halfling,
        abilityScores: [8, 16, 14, 8, 16, 10],
        spells: null,
        maxSpellSlots: null,
        currSpellSlots: null,
        maxHitPoints: 10,
        currHitPoints: 10,
        armorClass: 16,
        speed: 30,
        hitDice: 8,
      ),
      CharacterModel(
        name: "Nammath Zenriel",
        charClass: paladin,
        subclass: null,
        background: guildArtisan,
        race: dragonborn,
        abilityScores: [16, 8, 14, 10, 8, 16],
        spells: null,
        maxSpellSlots: null,
        currSpellSlots: null,
        maxHitPoints: 12,
        currHitPoints: 12,
        armorClass: 9,
        speed: 30,
        hitDice: 10,
      ),
      CharacterModel(
        name: "Maevlen Darkhammer",
        charClass: ranger,
        subclass: null,
        background: outlander,
        race: dwarf,
        abilityScores: [10, 16, 14, 8, 16, 8],
        spells: null,
        maxSpellSlots: null,
        currSpellSlots: null,
        maxHitPoints: 12,
        currHitPoints: 12,
        armorClass: 13,
        speed: 30,
        hitDice: 10,
      ),
      CharacterModel(
        name: "Ifni Pinesnout",
        charClass: rogue,
        subclass: null,
        background: criminal,
        race: human,
        abilityScores: [8, 16, 14, 8, 16, 10],
        spells: null,
        maxSpellSlots: null,
        currSpellSlots: null,
        maxHitPoints: 10,
        currHitPoints: 10,
        armorClass: 13,
        speed: 30,
        hitDice: 8,
      ),
      CharacterModel(
        name: "Ereon Hilldance",
        charClass: sorcerer,
        subclass: draconicBloodline,
        background: urchin,
        race: halfling,
        abilityScores: [8, 16, 14, 8, 10, 16],
        spells: [fireBolt, mageHand, shockingGrasp, acidSplash, shield, burningHands],
        maxSpellSlots: 2,
        currSpellSlots: 2,
        maxHitPoints: 9,
        currHitPoints: 9,
        armorClass: 16,
        speed: 30,
        hitDice: 6,
      ),
      CharacterModel(
        name: "Nahiri",
        charClass: warlock,
        subclass: fiend,
        background: charlatan,
        race: tiefling,
        abilityScores: [8, 14, 16, 8, 10, 16],
        spells: [eldritchBlast, mageHand, hex, hellishRebuke],
        maxSpellSlots: 1,
        currSpellSlots: 1,
        maxHitPoints: 11,
        currHitPoints: 11,
        armorClass: 12,
        speed: 30,
        hitDice: 8,
      ),
      CharacterModel(
        name: "Elamaer Stoneflow",
        charClass: wizard,
        subclass: null,
        background: sage,
        race: elf,
        abilityScores: [8, 14, 16, 16, 8, 10],
        spells: [fireBolt, mageHand, shockingGrasp, acidSplash, findFamiliar, burningHands, magicMissile, detectMagic, mageArmor, sleep],
        maxSpellSlots: 2,
        currSpellSlots: 2,
        maxHitPoints: 9,
        currHitPoints: 9,
        armorClass: 12,
        speed: 30,
        hitDice: 6,
      ),
    ];
  }

  // getter and setter
  List<CharacterModel> get getCharacterList => characterList;
  set setCharacterList(List<CharacterModel> newCharacterList) {
    characterList = newCharacterList;
    notifyListeners();
  }

  // adding new character
  void addCharacter(CharacterModel newCharacter) {
    characterList.add(newCharacter);
    notifyListeners();
  }
}